# Node.js React Web App to Linux on Azure
# Build a Node.js React app and deploy it to Azure as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - master

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'adc2be57-23eb-42e7-b7d9-9760ae134cd2'

  # Web app name
  webAppName: 'color-app'

  # Environment name
  prodEnvironmentName: 'production'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '>=16.x.x'
    
    # - script: |
    #     npm ci
    #     npm run build --if-present
    #   displayName: 'npm install, build'
    
    - task: Npm@1
      displayName: 'Installing dependencies'
      inputs:
        command: 'install'
        workingDir: '$(System.DefaultWorkingDirectory)'
    
    - task: Npm@1
      displayName: 'Build project to production'
      inputs:
        command: 'custom'
        workingDir: '$(System.DefaultWorkingDirectory)'
        customCommand: 'run build --if-present'

    - task: ArchiveFiles@2
      displayName: 'Archive files to publish folder'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    # Deprecated
    # - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    #   artifact: drop
    
    - task: PublishPipelineArtifact@1
      displayName: 'Publish pipeline artifacts'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        artifact: '$(Build.BuildId)'
        publishLocation: 'pipeline'


- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: $(prodEnvironmentName)
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              artifactName: '$(Build.BuildId)'
              targetPath: '$(Pipeline.Workspace)'

          - task: AzureRmWebAppDeployment@4
            displayName: 'Azure App Service Deploy: '
            inputs:
              azureSubscription: $(azureSubscription)
              appType: webAppLinux
              WebAppName: $(webAppName)
              packageForLinux: '$(Pipeline.Workspace)/$(Build.BuildId).zip'
              RuntimeStack: 'NODE|16-lts'
              StartupCommand: 'npm run start'
              # ScriptType: 'Inline Script'
              # InlineScript: |
              #   npm install
              #   npm run build --if-present